project:
  type: website
  output-dir: docs

website:
  title: "kiryawagner.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: style.scss
    mainfont: Nunito
    css: styles.css
    toc: true
    page-layout: full

editor: visual
