project:
  type: website
  output-dir: docs

website:
  title: "Kirya Wagner"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Progress.qmd
      - Travel.qmd

format:
  html:
    theme: 
    - cosmo
    - styles.scss
    mainfont: Rokkitt
    css: styles.css
    toc: true
    page-layout: full

editor: visual
