---
title: "School & Work"
---

## Relevant Coursework 

**STEM:** General Chemistry • Introduction to Biology • Plant and Animal Physiology • Introduction to Ecology and Evolution • Introduction to Microbes, Plants, and Animals • Biology and Chemistry Lab • Calculus • Environmental Data Science

**Environmental Studies:** Introduction to Environmental Studies • Critical Thinking and Reason in Environmental Studies • Low Carbon Environment

## Skills 
-R studio / Data Analysis & Visualization 

-HTML (web development)

-Photoshop 

-Microscope dissection

-CPR / First Aid


## Research Projects
[This is a research poster I did on genes involved in chemotaxis in C. elegans.](https://acrobat.adobe.com/id/urn:aaid:sc:VA6C2:b4da062c-7ffd-4bd1-aaff-38b4f6e2ff3d)

[This is a research paper I did on the inheritance patterns of eye color genes in drosphila.](https://acrobat.adobe.com/id/urn:aaid:sc:VA6C2:c924079a-fb21-4e90-81e6-1b82147648ec)


## Experience

**Animal Care Assistant, SB Wildlife Care Network, Santa Barbara, CA** *March 2024 - Present*

-Keep track of strict feeding schedules ensuring all wildlife properly cared for.

-Maintain sanitary conditions throughout the facility by cleaning laundry, dishes, and equipment to establish a safe, hygienic environment for wildlife. 

-Properly administer medications, give subcutaneous fluids, and identify common pathogens through microscopes.

**Camp Counselor, Hephatha Lutheran School, Anaheim Hills, CA** *June 2023 - August 2023*

-Collaborated effectively with other counselors and staff members to keep camp operations seamless.

-Committed to maintaining a safe and secure camp environment, by completing CPR and first aid training.

-Demonstrated effective organizational skills to plan and coordinate camp activities and meals, as well as clean and organize classrooms.

**Sales Floor Associate, Kohls, Corona, CA** *July 2022 - Sept 2022*

-Provided exceptional customer service by answering phone calls, assisting shoppers, and addressing issues promptly.

-Adapted between diverse roles such as cash register operations, customer service, and dressing room attendant.
